url: http://eliscleaningservices.github.io/
baseurl:

# Site settings
title: Elizabeth's Cleaning Services
email: eliquiroz20@gmail.com
description: "Northwest Minneapolis Suburbs Home Cleaning Services"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FDE74C
  secondary: FDE74C
  secondary-dark: 333

# Postal address (add as many lines as necessary)
address:
  - line: Minneapolis, MN 55311

# Build settings
markdown: kramdown
permalink: pretty
